### ISSUE TITLE
Behaviour when service is undefined

### ISSUE THREAD

**Issue by foretspaisibles** [copyleft/aws-sign4#5]
When the signing function is called with `service` bound to `nil`, the credential scope value features the string `nil` which should probably not happen.

The correct behaviour should be to either:

- Signal an error, with a retry allowing to provide a service string.
- Provide a sensible default string value for the service. This could be `"service"` as in AWS test suite for signv4, the empty string or a phony value `"this-is-not-an-actual-service-name"`.

My personal preference goes to the first possibility. What do you think?

**Comment by bakketun** [comment]
The three parameters without any sensible default are service, path and host. I've updated the code signal an error if any of these are missing.

**Comment by foretspaisibles** [comment]
Thanks!
